<?php
define('_ROOT_URL', "https://www.489501.jp/kotei/");
#define('_ROOT_URL', "http://192.168.98.192/kotei-k/");
#define('_ROOT_URL', "https://203.196.20.121/kotei-k/");

define("_LIBRARY_ROOT", "D:/xampp/htdocs/kotei/SPFW/");
define("_DOCUMENT_ROOT", "D:/xampp/htdocs/kotei/httpdocs/");


define("_MAIN_DB", "kojikotei");
define("_HOST_NAME", "localhost");
define("_USER_NAME", "root");
define("_PASSWD", "");

#489 工事統一化
define("_MAIN_DB489", "skoji");
define("_HOST_NAME489", "localhost");
define("_USER_NAME489", "root");
define("_PASSWD489", "");

# For KenmeiSystemDB
#define("_MAIN_DB2", "Milkey1.world");
#define("_HOST_NAME2", "localhost");
#define("_USER_NAME2", "ORCLAIP");
#define("_PASSWD2", "");

#
define("_SEND_FROM", "info@nespe.jp");


#
define("_ACCEPT_DOMAIN", "489501.jp");


#
define("_ADMIN_EMAIL", "info@nespe.jp");


include_once _LIBRARY_ROOT . 'inc/system.properties';
include_once _LIBRARY_ROOT . 'inc/489.properties';
?>
