<?php
define('_ROOT_URL', "http://localhost/");
#define('_ROOT_URL', "http://192.168.98.192/hochiki-k/");
#define('_ROOT_URL', "https://203.196.20.121/hochiki-k/");
define('_ROOT_URL2', "http://localhost/");

define("_LIBRARY_ROOT", "C:/xampp/htdocs/hochiki/SPFW/");
define("_DOCUMENT_ROOT", "C:/xampp/htdocs/hochiki/httpdocs/");


define("_MAIN_DB", "kojihochiki");
define("_HOST_NAME", "localhost");
define("_USER_NAME", "root");
define("_PASSWD", "");

#489 工事統一化
define("_MAIN_DB489", "skoji");
define("_HOST_NAME489", "localhost");
define("_USER_NAME489", "root");
define("_PASSWD489", "");

# For SMSシステム
define("_MAIN_DBsms", "sms");
define("_HOST_NAMEsms", "localhost");
define("_USER_NAMEsms", "root");
define("_PASSWDsms", "");

#
define("_SEND_FROM", "info@nespe.jp");


#
define("_ACCEPT_DOMAIN", "489501.jp");


#
define("_ADMIN_EMAIL", "info@nespe.jp");


include_once _LIBRARY_ROOT . 'inc/system.properties';
include_once _LIBRARY_ROOT . 'inc/489.properties';
include_once _LIBRARY_ROOT . 'inc/Tenken.properties';
